on:
  push:
  pull_request:
    types: [labeled]

name: Issue Comments
jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo $GITHUB_REF
      - run: echo ${{ github.context.payload.pull_request.head.ref }}
      - name: Check for Command
        run: |
          echo test >> b.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add b.txt
          git commit -m "b.txt"
        if: github.event.label.name == 'toc'
      # - name: Git push
      #   uses: ad-m/github-push-action@v0.5.0
      #   with:
      #     branch: 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Check for Command
      #   run: echo "test bug"
      #   if: github.event.label.name == 'bug'
