on:
  push:
  pull_request:
    types: [labeled]

name: Issue Comments
jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Set output
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF:11}
      - run: echo ${{ steps.vars.outputs.branch }}
      - run: echo $GITHUB_REF
      - run: echo ${{ github.context.payload.pull_request.head.ref }}
      - run: echo ${{ github.context }}
      - name: Check for Command
        run: |
          echo test >> b.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add b.txt
          git commit -m "b.txt"
        if: github.event.label.name == 'toc'
      - name: Git push
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: ${{ steps.vars.outputs.branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
