on:
  pull_request:
    types: [labeled]

name: Issue Comments
jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check for Command
        run: |
          echo test >> b.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add b.txt
          git commit -m "b.txt"
          git push
        if: github.event.label.name == 'toc'
      - name: Check for Command
        run: echo "test bug"
        if: github.event.label.name == 'bug'
