on:
  pull_request:
    types: [labeled]

name: Issue Comments
jobs:
  check_comments:
    steps:
      - name: Check for Command
        run: echo "Runs on all toc commands"
        if: github.event.label.name == 'toc'
      - name: Check for Command
        run: echo "test bug"
        if: github.event.label.name == 'bug'
